// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// +build go1.10,integration

package s3_test

import (
	"context"
	"testing"
	"time"

	"github.com/aws/mateuszwojcikcc/aws"
	"github.com/aws/mateuszwojcikcc/aws/awserr"
	"github.com/aws/mateuszwojcikcc/aws/request"
	"github.com/aws/mateuszwojcikcc/awstesting/integration"
	"github.com/aws/mateuszwojcikcc/service/s3"
)

var _ aws.Config
var _ awserr.Error
var _ request.Request

func TestInteg_00_ListBuckets(t *testing.T) {
	ctx, cancelFn := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancelFn()

	sess := integration.SessionWithDefaultRegion("us-west-2")
	svc := s3.New(sess)
	params := &s3.ListBucketsInput{}
	_, err := svc.ListBucketsWithContext(ctx, params, func(r *request.Request) {
		r.Handlers.Validate.RemoveByName("core.ValidateParametersHandler")
	})
	if err != nil {
		t.Errorf("expect no error, got %v", err)
	}
}
