// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package awsendpointdiscoverytest

import (
	"github.com/aws/mateuszwojcikcc/private/protocol"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{}
